/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AppHome {
    'raceseries': RaceSeries[];
  }
  interface AppHomeAttributes extends StencilHTMLAttributes {
    'raceseries'?: RaceSeries[];
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface ContactPage {
    'success': boolean;
  }
  interface ContactPageAttributes extends StencilHTMLAttributes {
    'success'?: boolean;
  }

  interface ScrollHeader {
    'defaultHref': string;
    'headerTitle': string;
    'img': string;
  }
  interface ScrollHeaderAttributes extends StencilHTMLAttributes {
    'defaultHref'?: string;
    'headerTitle'?: string;
    'img'?: string;
  }

  interface SeriesPage {
    'series': RaceSeries;
  }
  interface SeriesPageAttributes extends StencilHTMLAttributes {
    'series'?: RaceSeries;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppRoot': Components.AppRoot;
    'ContactPage': Components.ContactPage;
    'ScrollHeader': Components.ScrollHeader;
    'SeriesPage': Components.SeriesPage;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-root': Components.AppRootAttributes;
    'contact-page': Components.ContactPageAttributes;
    'scroll-header': Components.ScrollHeaderAttributes;
    'series-page': Components.SeriesPageAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLContactPageElement extends Components.ContactPage, HTMLStencilElement {}
  var HTMLContactPageElement: {
    prototype: HTMLContactPageElement;
    new (): HTMLContactPageElement;
  };

  interface HTMLScrollHeaderElement extends Components.ScrollHeader, HTMLStencilElement {}
  var HTMLScrollHeaderElement: {
    prototype: HTMLScrollHeaderElement;
    new (): HTMLScrollHeaderElement;
  };

  interface HTMLSeriesPageElement extends Components.SeriesPage, HTMLStencilElement {}
  var HTMLSeriesPageElement: {
    prototype: HTMLSeriesPageElement;
    new (): HTMLSeriesPageElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-root': HTMLAppRootElement
    'contact-page': HTMLContactPageElement
    'scroll-header': HTMLScrollHeaderElement
    'series-page': HTMLSeriesPageElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'contact-page': HTMLContactPageElement;
    'scroll-header': HTMLScrollHeaderElement;
    'series-page': HTMLSeriesPageElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
